#pragma once

#include <shared/Common.h>

namespace Firelands {

/// Opcodes share a sequence of these markers (movement status elements, MSE).
/// Values follow the reference core `MovementStructures` layout used by this client.
enum MovementStatusElements : uint16_t {
  MSEHasGuidByte0,
  MSEHasGuidByte1,
  MSEHasGuidByte2,
  MSEHasGuidByte3,
  MSEHasGuidByte4,
  MSEHasGuidByte5,
  MSEHasGuidByte6,
  MSEHasGuidByte7,
  MSEHasMovementFlags,
  MSEHasMovementFlags2,
  MSEHasTimestamp,
  MSEHasOrientation,
  MSEHasTransportData,
  MSEHasTransportGuidByte0,
  MSEHasTransportGuidByte1,
  MSEHasTransportGuidByte2,
  MSEHasTransportGuidByte3,
  MSEHasTransportGuidByte4,
  MSEHasTransportGuidByte5,
  MSEHasTransportGuidByte6,
  MSEHasTransportGuidByte7,
  MSEHasTransportTime2,
  MSEHasVehicleId,
  MSEHasPitch,
  MSEHasFallData,
  MSEHasFallDirection,
  MSEHasSplineElevation,
  MSEHasSpline,
  MSEHasHeightChangeFailed,

  MSEGuidByte0,
  MSEGuidByte1,
  MSEGuidByte2,
  MSEGuidByte3,
  MSEGuidByte4,
  MSEGuidByte5,
  MSEGuidByte6,
  MSEGuidByte7,
  MSEMovementFlags,
  MSEMovementFlags2,
  MSETimestamp,
  MSEPositionX,
  MSEPositionY,
  MSEPositionZ,
  MSEOrientation,
  MSETransportGuidByte0,
  MSETransportGuidByte1,
  MSETransportGuidByte2,
  MSETransportGuidByte3,
  MSETransportGuidByte4,
  MSETransportGuidByte5,
  MSETransportGuidByte6,
  MSETransportGuidByte7,
  MSETransportPositionX,
  MSETransportPositionY,
  MSETransportPositionZ,
  MSETransportOrientation,
  MSETransportSeat,
  MSETransportTime,
  MSETransportTime2,
  MSETransportVehicleId,
  MSEPitch,
  MSEFallTime,
  MSEFallVerticalSpeed,
  MSEFallCosAngle,
  MSEFallSinAngle,
  MSEFallHorizontalSpeed,
  MSESplineElevation,

  MSECounter,

  MSEZeroBit,
  MSEOneBit,
  MSEFlushBits,
  MSEEnd,
  MSEExtraElement,
  MSEExtraFloat,
  MSEExtraInt8,
  MSEExtraTwoBits,
};

} // namespace Firelands
