-- Generated by tools/merge_migrations.py — do not edit by hand.
-- Regenerate: python3 tools/merge_migrations.py  (or: cmake --build build --target merge-migrations)
-- Marks sql/bundled (except zz_*.sql), sql/init, sql/migrations as applied.

CREATE DATABASE IF NOT EXISTS `firelands_auth`;

CREATE TABLE IF NOT EXISTS `firelands_auth`.`schema_migrations` (
  `migration` VARCHAR(255) NOT NULL,
  `applied_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`migration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `firelands_auth`.`schema_migrations` (`migration`) VALUES
  ('firelands_auth.sql'),
  ('firelands_characters.sql'),
  ('firelands_world.sql'),
  ('auth_schema.sql'),
  ('characters_schema.sql'),
  ('world_schema.sql'),
  ('31_world_creature_template_gossip_menu_id.sql'),
  ('32_world_gossip_tables.sql'),
  ('33_world_npc_text.sql'),
  ('34_world_npc_text_data.sql'),
  ('35_world_gossip_data.sql');
